name: diabetes-env
channels:
    - defaults
dependencies:
    - python=3.10
    - pip
    - pip:
          - mlflow==2.9.2
          - scikit-learn
          - pandas
          - numpy
          - matplotlib
          - seaborn
