name: diabetes-env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - pip:
          - mlflow
          - scikit-learn
          - pandas
          - matplotlib
          - seaborn
          - numpy
