name: diabetes-env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - pip:
          - mlflow==2.9.2
          - scikit-learn
          - pandas
          - matplotlib
          - seaborn
          - numpy
          - importlib-metadata<5.0
