name: diabetes-training-env

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.9
    - pip
    - pip:
          - mlflow>=2.6.0
          - scikit-learn
          - pandas
          - numpy
          - matplotlib
          - seaborn
