name: CI Workflow MLflow

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install MLflow
              run: pip install mlflow

            - name: Run MLflow Project
              run: mlflow run MLProject --env-manager local

            - name: Upload confusion matrix artifact
              uses: actions/upload-artifact@v4
              with:
                  name: confusion-matrix
                  path: MLProject/confusion_matrix.png
