name: CI Workflow MLflow

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  python-version: "3.10"
                  activate-environment: diabetes-env
                  environment-file: MLProject/conda.yaml

            - name: Install MLflow (pastikan ada di PATH)
              run: conda run -n diabetes-env pip install mlflow==2.13.0

            - name: Run MLflow Project
              run: conda run -n diabetes-env mlflow run MLProject --env-manager conda
